theme: jekyll-theme-cayman
title: RiseArc Legal
description: Official Privacy Policy and EULA for the RiseArc app.
show_downloads: false
url: https://1inzone.app
include: [".well-known"]
exclude: ["README.md"]
